### ISSUE TITLE
Logo Collection will not embed (from an iCloud.com webpage) 

### ISSUE THREAD

**Issue by LegendusMaximus** [logocollection/logocollection.github.io#1]
Hi,
I have created logocollection.github.io to showcase (embed onto the site) an iCloud shared album which is publicly visible on the web if you have the link. To find this Shared album cliak bug at the bottom of logocollection.github.io.
I cannot seem to embed my shared album called "Logo Collection" into the website though.
Do Apple have some block on this?
It would be great if you could help.
From LM

**Comment by dumbledad** [comment]
The prognosis is not good: https://stackoverflow.com/a/38269964/575530

**Comment by LegendusMaximus** [comment]
Thanks for this  @dumbledad, I "mppos  every you cannot embed iCloud shar  ed albumns into Github Pages.
I will open another issue relating to this as a long.term problem.
Thank you,
LM
